language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO='django>=1.4,<1.5'
  - DJANGO='django>=1.5,<1.6'
  - DJANGO='django>=1.6,<1.7'
  - DJANGO='django>=1.7,<1.8'
  - DJANGO='django>=1.8,<1.9'
  - DJANGO='django>=1.9,<1.10'

install:
  - pip install $DJANGO
  - pip install -r requirements.txt

script: python setup.py test

matrix:
  exclude:
    - python: 3.4
      env: DJANGO='django>=1.4,<1.5'
    - python: 3.5
      env: DJANGO='django>=1.4,<1.5'
  allow_failures:
    - python: 3.5
      env: DJANGO='django>=1.5,<1.6'
    - python: 3.5
      env: DJANGO='django>=1.6,<1.7'
    - python: 3.5
      env: DJANGO='django>=1.7,<1.8'

